# Generated by Django 5.2 on 2025-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='empi_ID',
            new_name='emp_id',
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emp',
            name='working',
            field=models.BooleanField(max_length=True),
        ),
    ]
